# Generated by Django 3.1.7 on 2021-04-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20210414_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='background_image',
            field=models.ImageField(default='image/1.jpeg', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='image/1.jpeg', upload_to='image/'),
        ),
    ]
