# Generated by Django 3.1.7 on 2021-04-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_auto_20210414_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='background_image',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
