# Generated by Django 3.1.5 on 2021-04-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_auto_20210414_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='background_image',
            field=models.ImageField(blank=True, default='image/Otaku.jpg', upload_to='profiles/image/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='image/Otaku.jpg', upload_to='profiles/image/'),
        ),
    ]
